In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Probability of Default

* Firstly define the target, what quanlifies a company as defaulted
*

In [ ]:
{
    "Profitability Metrics": [
        "Earnings Before Interest and Taxes (EBIT)",
        "Sales (Revenue)",

    ],
    "Operating Metrics": [
        "Research & Development (R&D) Expenses",
        "Operating Expenses",
        "Cost of Goods Sold (COGS)",
        "Operating Leverage",
        "Sales Volatility",

    ],
    "Liquidity Metrics": [
        "Accounts Receivable (A/R)",
        "Average Inventory",
        "Accounts Payable (A/P)",
        "Accrued Expenses (A/E)",
        "Marketable Securities (Mkt Sec)",
        "Short-Term Debt (ST Debt)",
        "Current Ratio",
        "Quick Ratio",
        "(Cash + Mkt Sec) / ST Debt"
    ],
    "Debt Metrics": [
        "Interest Expense",
        "Debt",
        "Net Debt",
        "Preferred Stock",
        "Book Capitalization",
        "Senior Debt",
        "Tangible Assets",
        "Debt / Revenues",
        "Debt / EBITDA",
        "(Debt + Preferred Stk) /  EBITDA",
        "Debt / Book Capitalization",
        "(Cash + Mkt Sec) / Debt"
    ],
    "Cash Flow Metrics": [
        "Funds From Operations (FFO)",
        "Retained Cash Flow (RCF)",
        "Cash Flow from Operations (CFO)",
        "Free Cash Flow (FCF)",
        "Change in Working Capital (WC)"
    ],
    "Receivables Metrics": [
        "A/R Reserve",
        "Gross Receivables",
        "A/R Days on Hand",
        "A/R Turnover"
    ],
}

In [ ]:
metrics = {
    "Profitability Metrics": [],
    "Liquidity Metrics": [],
    "Efficiency Metrics": [],
    
    
}

In [3]:
import pandas as pd

# Sample financial data for a company over 3 years
data = {
    'Year': [2021, 2022, 2023],
    'Working Capital': [50000, 45000, 40000],
    'Total Assets': [200000, 210000, 220000],
    'EBIT': [25000, 23000, 20000],
    'Total Liabilities': [150000, 160000, 170000],
    'Sales': [100000, 105000, 110000]
}

df = pd.DataFrame(data)

# Calculate financial ratios
df['A'] = df['Working Capital'] / df['Total Assets']
df['C'] = df['EBIT'] / df['Total Assets']

# Calculate yearly changes for dynamic analysis
df['Change in A'] = df['A'].diff()
df['Change in C'] = df['C'].diff()

# Simple dynamic Z'-Score components calculation (focusing on trends in A and C)
# Note: This is a simplified approach for demonstration. Consider adjusting weights and components as needed.
df['Dynamic Z\'-Score Indicator'] = df['Change in A'] + df['Change in C']

print(df[['Year', 'Dynamic Z\'-Score Indicator']])

   Year  Dynamic Z'-Score Indicator
0  2021                         NaN
1  2022                   -0.051190
2  2023                   -0.051082

In [3]:
import pandas as pd
import numpy as np

# Sample DataFrame with financial ratios
data = {
    'Return_on_Assets': [0.05, 0.03, -0.02],
    'Operating_Margin_Ratio': [0.15, 0.10, 0.05],
    'Net_Profit_Margin': [0.10, 0.08, -0.05],
    'Debt_to_EBITDA': [4, 6, 10],
    'EBITDA_to_Interest_Expense': [2.5, 1.5, 0.5],
    'Asset_Turnover': [0.7, 0.6, 0.4]
}
df = pd.DataFrame(data)

# Define weights for each ratio based on their impact on default risk
weights = {
    'Return_on_Assets': 1,
    'Operating_Margin_Ratio': 1,
    'Net_Profit_Margin': 1,
    'Debt_to_EBITDA': 2,  # Higher impact
    'EBITDA_to_Interest_Expense': 2,  # Higher impact
    'Asset_Turnover': 1
}

# Calculate weighted score for each entity
for ratio in weights:
    df[ratio + '_weighted'] = df[ratio] * weights[ratio]

# Sum weighted scores to get a composite score indicating default risk
df['default_risk_score'] = df[[col for col in df.columns if 'weighted' in col]].sum(axis=1)

# Interpretation of the default risk score could be domain-specific
# Here, we simply label entities with scores below a certain threshold as 'high risk' for default
threshold = df['default_risk_score'].quantile(0.33)  # Example threshold, adjust based on analysis
df['default_risk'] = np.where(df['default_risk_score'] < threshold, 'High Risk', 'Low Risk')

print(df[['default_risk_score', 'default_risk']])

   default_risk_score default_risk
0               14.00    High Risk
1               15.81     Low Risk
2               21.38     Low Risk

In [18]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Example DataFrame
# df = pd.DataFrame(data)

data = {
    'Return_on_Assets': [0.05, 0.03, -0.02],
    'Operating_Margin_Ratio': [0.15, 0.10, 0.05],
    'Net_Profit_Margin': [0.10, 0.08, -0.05],
    'Debt_to_EBITDA': [4, 6, 10],
    'EBITDA_to_Interest_Expense': [2.5, 1.5, 0.5],
    'Asset_Turnover': [0.7, 0.6, 0.4]
}
df = pd.DataFrame(data)


# Normalize the ratios
scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df[['Return_on_Assets', 'Operating_Margin_Ratio', 'Net_Profit_Margin', 'Debt_to_EBITDA', 'EBITDA_to_Interest_Expense', 'Asset_Turnover']]), columns=['RoA', 'OMR', 'NPM', 'DtE', 'EtoIE', 'AT'])

# Weighted score (example weights)
weights = np.array([0.2, 0.15, 0.15, 0.25, 0.2, 0.05])
df_scaled['composite_score'] = df_scaled.dot(weights)

# Define default based on composite score threshold
threshold = np.percentile(df_scaled['composite_score'], 10)  # bottom 10% as at risk
df['default'] = (df_scaled['composite_score'] < threshold).astype(int)

In [10]:
import pandas as pd
import numpy as np

# Placeholder function to convert a ratio to a score
def score_ratio(ratio, healthy_range, inverse=False):
    """
    Converts a financial ratio to a score based on its deviation from a healthy range.
    :param ratio: The financial ratio value.
    :param healthy_range: A tuple indicating the healthy range of values for the ratio.
    :param inverse: Set to True if lower values are better for the ratio.
    :return: A score as a float.
    """
    if inverse:
        if ratio < healthy_range[0]:
            return (healthy_range[0] - ratio) / healthy_range[0]
        elif ratio > healthy_range[1]:
            return -(ratio - healthy_range[1]) / healthy_range[1]
    else:
        if ratio > healthy_range[1]:
            return (ratio - healthy_range[1]) / healthy_range[1]
        elif ratio < healthy_range[0]:
            return -(healthy_range[0] - ratio) / healthy_range[0]
    return 0  # Ratio is within the healthy range

# Example of scoring and weighting
df = pd.DataFrame({
    'Return_on_Assets': [.05, -.02, .1],
    'Operating_Margin_Ratio': [.15, .05, -.1],
    'Net_Profit_Margin': [.10, .03, -.05],
    'Debt_to_EBITDA': [3, 5, 10],
    'EBITDA_to_Interest_Expense': [2.5, 1, .5],
    'Asset_Turnover': [1.5, 2, .8]
})

weights = {
    'Return_on_Assets': 2,
    'Operating_Margin_Ratio': 1.5,
    'Net_Profit_Margin': 1.5,
    'Debt_to_EBITDA': -2,
    'EBITDA_to_Interest_Expense': -2,
    'Asset_Turnover': 1
}

healthy_ranges = {
    'Return_on_Assets': (0.02, 0.15),
    'Operating_Margin_Ratio': (0.10, 0.30),
    'Net_Profit_Margin': (0.05, 0.20),
    'Debt_to_EBITDA': (1, 4),
    'EBITDA_to_Interest_Expense': (2, 6),
    'Asset_Turnover': (0.5, 2)
}

# Calculate scores for each company
for ratio in healthy_ranges:
    df[f'{ratio}_score'] = df[ratio].apply(lambda x: score_ratio(x, healthy_ranges[ratio], inverse=ratio in ['Debt_to_EBITDA', 'EBITDA_to_Interest_Expense']))

# Calculate composite risk score
df['Composite_Risk_Score'] = sum(df[f'{ratio}_score'] * weight for ratio, weight in weights.items())

# Interpret the composite risk score
# Here you would define thresholds based on the distribution of composite scores
# For simplicity, let's assume a higher score indicates higher risk
df['Risk_Category'] = pd.cut(df['Composite_Risk_Score'], bins=3, labels=['Low', 'Medium', 'High'])

print(df[['Composite_Risk_Score', 'Risk_Category']])

   Composite_Risk_Score Risk_Category
0                  0.00          High
1                 -5.85           Low
2                 -4.50           Low

In [11]:
df

,Return_on_Assets,Operating_Margin_Ratio,Net_Profit_Margin,Debt_to_EBITDA,EBITDA_to_Interest_Expense,Asset_Turnover,Return_on_Assets_score,Operating_Margin_Ratio_score,Net_Profit_Margin_score,Debt_to_EBITDA_score,EBITDA_to_Interest_Expense_score,Asset_Turnover_score,Composite_Risk_Score,Risk_Category
0,0.05,0.15,0.10,3,2.5,1.5,0.0,0.0,0.0,0.00,0.00,0,0.00,High
1,-0.02,0.05,0.03,5,1.0,2.0,-2.0,-0.5,-0.4,-0.25,0.50,0,-5.85,Low
2,0.10,-0.10,-0.05,10,0.5,0.8,0.0,-2.0,-2.0,-1.50,0.75,0,-4.50,Low

In [12]:
import pandas as pd
import numpy as np

# Placeholder function to convert a ratio to a score
def score_ratio(ratio, healthy_range, inverse=False):
    """
    Converts a financial ratio to a score based on its deviation from a healthy range.
    :param ratio: The financial ratio value.
    :param healthy_range: A tuple indicating the healthy range of values for the ratio.
    :param inverse: Set to True if lower values are better for the ratio.
    :return: A score as a float.
    """
    if inverse:
        if ratio < healthy_range[0]:
            return (healthy_range[0] - ratio) / healthy_range[0]
        elif ratio > healthy_range[1]:
            return -(ratio - healthy_range[1]) / healthy_range[1]
    else:
        if ratio > healthy_range[1]:
            return (ratio - healthy_range[1]) / healthy_range[1]
        elif ratio < healthy_range[0]:
            return -(healthy_range[0] - ratio) / healthy_range[0]
    return 0  # Ratio is within the healthy range

# Example of scoring and weighting
data = {
    "Company": ["Company A", "Company B", "Company C", "Company D", "Company E", "Company F"],
    "Return_on_Assets": [0.02, 0.04, 0.07, 0.03, 0.05, 0.09],  # ROA: Poor, Fair, Good
    "Operating_Margin_Ratio": [0.03, 0.10, 0.20, 0.05, 0.12, 0.25],  # OMR: Poor, Fair, Good
    "Net_Profit_Margin": [0.02, 0.06, 0.12, 0.03, 0.07, 0.15],  # NPM: Poor, Fair, Good
    "Debt_to_EBITDA": [5.0, 3.5, 1.5, 4.0, 2.5, 1.0],  # D/E: High, Moderate, Low Risk
    "EBITDA_to_Interest_Expense": [1.2, 2.0, 3.5, 1.5, 2.5, 4.0],  # EBITDA/IE: Weak, Adequate, Strong
    "Asset_Turnover": [0.4, 0.8, 1.6, 0.5, 1.0, 2.0]  # AT: Low, Moderate, High Efficiency
}

df = pd.DataFrame(data)

weights = {
    'Return_on_Assets': 2,
    'Operating_Margin_Ratio': 1.5,
    'Net_Profit_Margin': 1.5,
    'Debt_to_EBITDA': -2,
    'EBITDA_to_Interest_Expense': -2,
    'Asset_Turnover': 1
}

healthy_ranges = {
    'Return_on_Assets': (0.02, 0.15),
    'Operating_Margin_Ratio': (0.10, 0.30),
    'Net_Profit_Margin': (0.05, 0.20),
    'Debt_to_EBITDA': (1, 4),
    'EBITDA_to_Interest_Expense': (2, 6),
    'Asset_Turnover': (0.5, 2)
}

# Calculate scores for each company
for ratio in healthy_ranges:
    df[f'{ratio}_score'] = df[ratio].apply(lambda x: score_ratio(x, healthy_ranges[ratio], inverse=ratio in ['Debt_to_EBITDA', 'EBITDA_to_Interest_Expense']))

# Calculate composite risk score
df['Composite_Risk_Score'] = sum(df[f'{ratio}_score'] * weight for ratio, weight in weights.items())

# Interpret the composite risk score
# Here you would define thresholds based on the distribution of composite scores
# For simplicity, let's assume a higher score indicates higher risk
df['Risk_Category'] = pd.cut(df['Composite_Risk_Score'], bins=3, labels=['Low', 'Medium', 'High'])

print(df[['Composite_Risk_Score', 'Risk_Category']])

   Composite_Risk_Score Risk_Category
0                 -2.45           Low
1                  0.00          High
2                  0.00          High
3                 -1.85           Low
4                  0.00          High
5                  0.00          High

In [8]:
df = pd.DataFrame({
    'Return_on_Assets': [.05, -.02, .1],
    'Operating_Margin_Ratio': [.15, .05, -.1],
    'Net_Profit_Margin': [.10, .03, -.05],
    'Debt_to_EBITDA': [3, 5, 5],
    'EBITDA_to_Interest_Expense': [2.5, 1, .5],
    'Asset_Turnover': [1.5, 2, .8]
})

In [9]:
df

,Return_on_Assets,Operating_Margin_Ratio,Net_Profit_Margin,Debt_to_EBITDA,EBITDA_to_Interest_Expense,Asset_Turnover
0,0.05,0.15,0.10,3,2.5,1.5
1,-0.02,0.05,0.03,5,1.0,2.0
2,0.10,-0.10,-0.05,10,0.5,0.8

In [13]:
import pandas as pd

# Original data
data = {
    "Company": ["ABC", "DEF", "GHI", "JKL", "MNO", "PQR"],
    "Return_on_Assets": [0.02, 0.04, 0.07, 0.03, 0.05, 0.09],
    "Operating_Margin_Ratio": [0.03, 0.10, 0.20, 0.05, 0.12, 0.25],
    "Net_Profit_Margin": [0.02, 0.06, 0.12, 0.03, 0.07, 0.15],
    "Debt_to_EBITDA": [5.0, 3.5, 1.5, 4.0, 2.5, 1.0],
    "EBITDA_to_Interest_Expense": [1.2, 2.0, 3.5, 1.5, 2.5, 4.0],
    "Asset_Turnover": [0.4, 0.8, 1.6, 0.5, 1.0, 2.0]
}

df = pd.DataFrame(data)

# New classification ranges for each metric
classification_ranges = {
    'Return_on_Assets': {'Poor': (None, 0.02), 'Fair': (0.02, 0.05), 'Good': (0.05, None)},
    'Operating_Margin_Ratio': {'Poor': (None, 0.10), 'Fair': (0.10, 0.20), 'Good': (0.20, None)},
    'Net_Profit_Margin': {'Poor': (None, 0.05), 'Fair': (0.05, 0.10), 'Good': (0.10, None)},
    'Debt_to_EBITDA': {'Good': (None, 2.0), 'Fair': (2.0, 4.0), 'Poor': (4.0, None)},  # Inverse logic
    'EBITDA_to_Interest_Expense': {'Poor': (None, 2.0), 'Fair': (2.0, 4.0), 'Good': (4.0, None)},
    'Asset_Turnover': {'Poor': (None, 0.5), 'Fair': (0.5, 1.5), 'Good': (1.5, None)}
}

# Function to classify metric values
def classify_metric(value, ranges):
    for classification, (low, high) in ranges.items():
        if low is None and value <= high:
            return classification
        elif high is None and value > low:
            return classification
        elif low is not None and high is not None and low <= value <= high:
            return classification
    return "Unknown"

# Apply classification to each metric
for metric, ranges in classification_ranges.items():
    inverse = metric in ['Debt_to_EBITDA']
    adjusted_ranges = {k: v if not inverse else v[::-1] for k, v in ranges.items()}
    df[f'{metric}_Class'] = df[metric].apply(classify_metric, args=(adjusted_ranges,))

# Displaying the classification results
df[['Company'] + [f'{metric}_Class' for metric in classification_ranges]]

,Company,Return_on_Assets_Class,Operating_Margin_Ratio_Class,Net_Profit_Margin_Class,Debt_to_EBITDA_Class,EBITDA_to_Interest_Expense_Class,Asset_Turnover_Class
0,Company A,Poor,Poor,Poor,Good,Poor,Poor
1,Company B,Fair,Poor,Fair,Good,Poor,Fair
2,Company C,Good,Fair,Good,Poor,Fair,Good
3,Company D,Fair,Poor,Poor,Good,Poor,Poor
4,Company E,Fair,Fair,Fair,Good,Fair,Fair
5,Company F,Good,Good,Good,Poor,Fair,Good

In [15]:
pd.DataFrame(data)

,Company,Return_on_Assets,Operating_Margin_Ratio,Net_Profit_Margin,Debt_to_EBITDA,EBITDA_to_Interest_Expense,Asset_Turnover
0,Company A,0.02,0.03,0.02,5.0,1.2,0.4
1,Company B,0.04,0.10,0.06,3.5,2.0,0.8
2,Company C,0.07,0.20,0.12,1.5,3.5,1.6
3,Company D,0.03,0.05,0.03,4.0,1.5,0.5
4,Company E,0.05,0.12,0.07,2.5,2.5,1.0
5,Company F,0.09,0.25,0.15,1.0,4.0,2.0

In [16]:
# Assign numerical values to classifications
classification_values = {'Poor': 1, 'Fair': 2, 'Good': 3}

# Function to compute deviation score for each company
def compute_deviation_score(row):
    scores = []
    for metric in classification_ranges:
        classification = row[f'{metric}_Class']
        metric_score = classification_values[classification]
        deviation = 3 - metric_score  # Compute deviation from "Good" (value 3)
        scores.append(deviation)
    return sum(scores)  # Return total deviation score for the company

# Apply the function to compute the deviation score for each company
df['Deviation_Score'] = df.apply(compute_deviation_score, axis=1)

# Optionally, sort the DataFrame by Deviation_Score to see which companies are closest to "Good" across all metrics
df_sorted_by_deviation = df.sort_values(by='Deviation_Score')

df_sorted_by_deviation[['Company', 'Deviation_Score'] + [f'{metric}_Class' for metric in classification_ranges]]

,Company,Deviation_Score,Return_on_Assets_Class,Operating_Margin_Ratio_Class,Net_Profit_Margin_Class,Debt_to_EBITDA_Class,EBITDA_to_Interest_Expense_Class,Asset_Turnover_Class
5,Company F,3,Good,Good,Good,Poor,Fair,Good
2,Company C,4,Good,Fair,Good,Poor,Fair,Good
4,Company E,5,Fair,Fair,Fair,Good,Fair,Fair
1,Company B,7,Fair,Poor,Fair,Good,Poor,Fair
3,Company D,9,Fair,Poor,Poor,Good,Poor,Poor
0,Company A,10,Poor,Poor,Poor,Good,Poor,Poor

In [24]:
import pandas as pd

# Initial data
data = {
    "Company": ["Company A", "Company B", "Company C", "Company D", "Company E", "Company F"],
    "Return_on_Assets": [0.02, 0.04, 0.07, 0.03, 0.05, 0.09],
    "Operating_Margin_Ratio": [0.03, 0.10, 0.20, 0.05, 0.12, 0.25],
    "Net_Profit_Margin": [0.02, 0.06, 0.12, 0.03, 0.07, 0.15],
    "Debt_to_EBITDA": [5.0, 3.5, 1.5, 4.0, 2.5, 1.0],
    "EBITDA_to_Interest_Expense": [1.2, 2.0, 3.5, 1.5, 2.5, 4.0],
    "Asset_Turnover": [0.4, 0.8, 1.6, 0.5, 1.0, 2.0]
}
df = pd.DataFrame(data)

# Classification values and ranges
classification_values = {'Poor': 1, 'Fair': 2, 'Good': 3}
classification_ranges = {
    'Return_on_Assets': {'Poor': (None, 0.02), 'Fair': (0.02, 0.05), 'Good': (0.05, None)},
    'Operating_Margin_Ratio': {'Poor': (None, 0.10), 'Fair': (0.10, 0.20), 'Good': (0.20, None)},
    'Net_Profit_Margin': {'Poor': (None, 0.05), 'Fair': (0.05, 0.10), 'Good': (0.10, None)},
    'Debt_to_EBITDA': {'Good': (None, 2.0), 'Fair': (2.0, 4.0), 'Poor': (4.0, None)},  # Note: Inverted logic for Debt to EBITDA
    'EBITDA_to_Interest_Expense': {'Poor': (None, 2.0), 'Fair': (2.0, 4.0), 'Good': (4.0, None)},
    'Asset_Turnover': {'Poor': (None, 0.5), 'Fair': (0.5, 1.5), 'Good': (1.5, None)}
}

# Function to classify metric values into "Poor", "Fair", and "Good"
def classify_metric(value, metric):
    ranges = classification_ranges[metric]
    for classification, (low, high) in ranges.items():
        if low is None and value <= high:
            return classification
        elif high is None and value > low:
            return classification
        elif low is not None and high is not None and low <= value <= high:
            return classification
    return "Unknown"

# Apply classification for each metric
for metric in classification_ranges.keys():
    df[f'{metric}_Class'] = df[metric].apply(lambda x: classify_metric(x, metric))

# Function to calculate overall score and classification
def calculate_and_classify_overall(row):
    scores = [classification_values[row[f'{metric}_Class']] for metric in classification_ranges]
    overall_score = sum(scores) / len(scores)
    overall_class = 'Good' if overall_score > 2.5 else 'Fair' if overall_score > 1.5 else 'Poor'
    return pd.Series([overall_score, overall_class], index=['Overall_Score', 'Overall_Class'])

# Calculate overall scores and classifications
df[['Overall_Score', 'Overall_Class']] =df.apply(calculate_and_classify_overall, axis=1)

In [26]:
df[['Company', 'Overall_Score', 'Overall_Class']]

     Company  Overall_Score Overall_Class
0  Company A       1.000000          Poor
1  Company B       1.666667          Fair
2  Company C       2.666667          Good
3  Company D       1.333333          Poor
4  Company E       2.000000          Fair
5  Company F       2.833333          Good

In [28]:
df[['Company', '']]

,Company,Return_on_Assets,Operating_Margin_Ratio,Net_Profit_Margin,Debt_to_EBITDA,EBITDA_to_Interest_Expense,Asset_Turnover,Return_on_Assets_Class,Operating_Margin_Ratio_Class,Net_Profit_Margin_Class,Debt_to_EBITDA_Class,EBITDA_to_Interest_Expense_Class,Asset_Turnover_Class,Overall_Score,Overall_Class
0,Company A,0.02,0.03,0.02,5.0,1.2,0.4,Poor,Poor,Poor,Poor,Poor,Poor,1.000000,Poor
1,Company B,0.04,0.10,0.06,3.5,2.0,0.8,Fair,Poor,Fair,Fair,Poor,Fair,1.666667,Fair
2,Company C,0.07,0.20,0.12,1.5,3.5,1.6,Good,Fair,Good,Good,Fair,Good,2.666667,Good
3,Company D,0.03,0.05,0.03,4.0,1.5,0.5,Fair,Poor,Poor,Fair,Poor,Poor,1.333333,Poor
4,Company E,0.05,0.12,0.07,2.5,2.5,1.0,Fair,Fair,Fair,Fair,Fair,Fair,2.000000,Fair
5,Company F,0.09,0.25,0.15,1.0,4.0,2.0,Good,Good,Good,Good,Fair,Good,2.833333,Good